# Generated by Django 5.0.4 on 2024-05-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.telefono'),
        ),
        migrations.AddField(
            model_name='email',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.nombre'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='Nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.nombre'),
        ),
    ]
