# Generated by Django 5.0.4 on 2024-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_nombre_remove_cliente_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='correo_e',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='telefono',
            name='num_tel',
            field=models.IntegerField(null=True),
        ),
    ]
