# Generated by Django 5.0.4 on 2024-05-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_email_correo_e_telefono_num_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='Nombre',
        ),
    ]
