# Generated by Django 5.0.4 on 2024-05-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_email_nombre_remove_telefono_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cliente.telefono'),
        ),
        migrations.AlterField(
            model_name='email',
            name='correo_e',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='num_tel',
            field=models.CharField(max_length=200),
        ),
    ]
