# Generated by Django 5.0.4 on 2024-05-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_correo_e_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo_e',
        ),
        migrations.RemoveField(
            model_name='email',
            name='correo_e',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='num_tel',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_rel', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nombre',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nombre_rel', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono_rel', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nombre',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
