# Generated by Django 5.0.4 on 2024-05-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMutante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('num_nivel', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Nivel del Mutante',
                'verbose_name_plural': 'Nivel de los Mutantes',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_real', models.CharField(max_length=100)),
                ('poderes', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('biografia', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
                ('fecha_creacion', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de creacion')),
                ('categoria_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaje.nivelmutante')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
    ]
