# Generated by Django 5.0.4 on 2024-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
