# Generated by Django 5.0.4 on 2024-05-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name': 'categoria de productos', 'verbose_name_plural': 'categoria de productos'},
        ),
    ]
