# Generated by Django 5.0.4 on 2024-05-22 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0002_alter_personaje_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
