# Generated by Django 5.0.4 on 2024-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0003_alter_personaje_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelmutante',
            options={'verbose_name': 'Nivel del Mutante'},
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_personajes/'),
        ),
    ]
