# Generated by Django 5.0.4 on 2024-05-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0004_alter_nivelmutante_options_personaje_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='biografia',
            new_name='descripcion',
        ),
    ]
