# Generated by Django 5.0.4 on 2024-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_productocategoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='num_serie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
