# Generated by Django 5.0.4 on 2024-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_personajes/'),
        ),
    ]
