# Generated by Django 5.0.4 on 2024-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_autor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='edad',
        ),
    ]
